/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Thu Sep  8 00:18:32 2016. */

#include "command.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Command_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Command, command, command, 0),
    PB_LAST_FIELD
};

const pb_field_t Response_fields[3] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, Response, success, success, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, Response, someValue, success, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
